import type { NativePoll } from '../domain/types.js';

export type DefaultPollTemplate = NativePoll & { key: string; category: string };

// The built-in bank is a last resort. Keys are stable so existing installations only seed new entries.
// A pipe separates options; no option label in this bank contains a pipe.
export const DEFAULT_POLL_TEMPLATES: readonly DefaultPollTemplate[] = [
  poll(
    'focus-aids',
    'Concentración',
    '¿Qué cosas te ayudan a concentrarte?',
    'Silencio|Música|Auriculares|Temporizador|Lista de tareas|Moverme|Bebida cerca|Estar a solas',
    true,
  ),
  poll(
    'focus-time',
    'Concentración',
    '¿En qué momento te resulta más fácil concentrarte?',
    'Mañana|Tarde|Noche|Madrugada|Depende del día',
  ),
  poll(
    'focus-break',
    'Concentración',
    '¿Qué pausa te ayuda a retomar una tarea?',
    'Caminar|Estirarme|Beber agua|Escuchar una canción|Mirar afuera|Cambiar de actividad',
    true,
  ),
  poll(
    'focus-distractions',
    'Concentración',
    '¿Qué suele interrumpir tu concentración?',
    'Notificaciones|Ruido|Conversaciones|Tareas pendientes|Cansancio|Cambios inesperados',
    true,
  ),
  poll('digital-dark-mode', 'Vida digital', '¿Sueles usar el teléfono en modo oscuro?', 'Sí|No'),
  poll(
    'digital-notifications',
    'Vida digital',
    '¿Qué notificaciones prefieres silenciar?',
    'Grupos|Redes sociales|Promociones|Noticias|Juegos',
    true,
  ),
  poll(
    'digital-offline',
    'Vida digital',
    '¿Qué haces cuando quieres alejarte un rato de las pantallas?',
    'Caminar|Leer|Dormir|Cocinar|Conversar|Crear algo|Escuchar música',
    true,
  ),
  poll(
    'digital-chat-pace',
    'Vida digital',
    '¿Cómo gestionas los chats cuando hay muchos mensajes?',
    'Los reviso al momento|Los leo después|Silencio algunos|Reviso solo los fijados',
  ),
  poll(
    'music-discovery',
    'Música',
    '¿Cómo descubres música nueva?',
    'Playlists|Recomendaciones automáticas|Videos o redes|Amigos|Series o películas|Buscando artistas|Radio',
    true,
  ),
  poll(
    'music-listening',
    'Música',
    '¿Cómo prefieres escuchar música normalmente?',
    'Playlist propia|Mix automático|Álbum completo|Canciones guardadas|Radio o stream|Depende del momento',
  ),
  poll(
    'music-moments',
    'Música',
    '¿En qué momentos sueles poner música?',
    'Al estudiar|Al trabajar|Al viajar|Al descansar|Al ordenar|Al caminar|Al crear algo',
    true,
  ),
  poll(
    'music-share',
    'Música',
    '¿Compartes canciones que te gustan con otras personas?',
    'Sí, a menudo|A veces|Casi nunca',
  ),
  poll(
    'gaming-platform',
    'Gaming',
    '¿Dónde juegas más a menudo?',
    'Teléfono|Consola|Computadora|En varias plataformas|No suelo jugar',
  ),
  poll(
    'gaming-company',
    'Gaming',
    '¿Cómo prefieres jugar?',
    'A solas|Con amistades|Con gente online|Depende del juego',
  ),
  poll(
    'gaming-attractions',
    'Gaming',
    '¿Qué te atrae de un juego?',
    'Historia|Explorar|Resolver desafíos|Crear cosas|Competir|Cooperar|Relajarme',
    true,
  ),
  poll(
    'gaming-session',
    'Gaming',
    '¿Qué haces cuando necesitas una pausa de una partida?',
    'Estirarme|Tomar agua|Cambiar de juego|Escuchar música|Salir un rato|Terminar la sesión',
    true,
  ),
  poll(
    'watch-format',
    'Entretenimiento',
    '¿Qué formato eliges más cuando tienes poco tiempo?',
    'Video corto|Episodio|Película|Podcast|Directo o stream|Lectura breve',
  ),
  poll(
    'watch-selection',
    'Entretenimiento',
    '¿Cómo eliges qué ver?',
    'Recomendación de alguien|Lista pendiente|Plataforma|Redes sociales|Busco por tema',
  ),
  poll(
    'watch-company',
    'Entretenimiento',
    '¿Prefieres ver una serie a solas o con alguien?',
    'A solas|Con alguien|Depende de la serie',
  ),
  poll(
    'watch-appeal',
    'Entretenimiento',
    '¿Qué hace que sigas una serie?',
    'Personajes|Historia|Humor|Misterio|Visuales|Episodios breves',
    true,
  ),
  poll(
    'hobby-week',
    'Hobbies',
    '¿Qué hobbies te gustaría retomar esta semana?',
    'Leer|Dibujar|Jugar|Cocinar|Fotografiar|Cuidar plantas|Armar algo|Aprender un tema',
    true,
  ),
  poll(
    'hobby-learning',
    'Hobbies',
    '¿Cómo te gusta aprender sobre un hobby?',
    'Tutoriales|Practicando|Comunidad online|Con alguien cercano|Leyendo',
  ),
  poll(
    'hobby-space',
    'Hobbies',
    '¿Dónde disfrutas más tus pasatiempos?',
    'En casa|Al aire libre|En un taller|En línea|Depende del hobby',
  ),
  poll(
    'hobby-sharing',
    'Hobbies',
    '¿Te gusta mostrar lo que haces en tus pasatiempos?',
    'Sí|Solo a personas cercanas|Prefiero guardarlo para mí',
  ),
  poll(
    'creative-start',
    'Creatividad',
    '¿Qué te ayuda a empezar un proyecto creativo?',
    'Una idea espontánea|Una consigna|Una referencia|Música|Materiales a mano|Un plazo corto',
    true,
  ),
  poll(
    'creative-medium',
    'Creatividad',
    '¿Qué formas de crear te interesan?',
    'Escribir|Dibujar|Fotografiar|Hacer música|Editar videos|Cocinar|Diseñar|Construir',
    true,
  ),
  poll(
    'creative-block',
    'Creatividad',
    '¿Qué haces cuando te quedas sin ideas?',
    'Descansar|Cambiar de actividad|Buscar referencias|Hablar con alguien|Empezar por algo pequeño',
    true,
  ),
  poll(
    'creative-sharing',
    'Creatividad',
    '¿Dónde prefieres compartir algo que creaste?',
    'Con amistades|En una comunidad online|En redes|En privado|Prefiero no compartirlo',
  ),
  poll(
    'rest-disconnect',
    'Descanso',
    '¿Qué haces para desconectarte un rato?',
    'Música|Series o videos|Gaming|Caminar|Dormir|Hablar con alguien|Estar a solas|Crear algo|Leer|No hacer nada',
    true,
  ),
  poll(
    'rest-quiet',
    'Descanso',
    '¿Qué ambiente prefieres para descansar?',
    'Silencioso|Con música suave|Con sonido de fondo|Al aire libre|Depende del momento',
  ),
  poll(
    'rest-short',
    'Descanso',
    '¿Cuánto tiempo de pausa te resulta útil durante el día?',
    'Unos minutos|Media hora|Una hora o más|Varía mucho',
  ),
  poll(
    'rest-weekend',
    'Descanso',
    '¿Qué incluyes en un fin de semana tranquilo?',
    'Dormir más|Ver algo|Jugar|Salir a caminar|Cocinar|Leer|No tener planes',
    true,
  ),
  poll(
    'sleep-routine',
    'Sueño',
    '¿Qué forma parte de tu rutina antes de dormir?',
    'Bajar la luz|Escuchar algo|Leer|Alejar el teléfono|Preparar el día siguiente',
    true,
  ),
  poll(
    'sleep-sound',
    'Sueño',
    '¿Con qué sonido te resulta más cómodo dormir?',
    'Silencio|Sonido ambiente|Música suave|Ventilador|Depende de la noche',
  ),
  poll(
    'sleep-schedule',
    'Sueño',
    '¿A qué hora te resulta más natural ir a dormir?',
    'Temprano|Cerca de medianoche|De madrugada|Cambia según el día',
  ),
  poll(
    'sleep-wakeup',
    'Sueño',
    '¿Qué te ayuda a arrancar la mañana?',
    'Luz natural|Una bebida|Música|Tiempo en silencio|Moverme un poco|Un plan claro',
    true,
  ),
  poll(
    'social-plan',
    'Socialización',
    '¿Qué tipo de plan social disfrutas más?',
    'Conversación tranquila|Juego compartido|Salir a comer|Paseo|Actividad creativa|Reunión online',
  ),
  poll(
    'social-recharge',
    'Socialización',
    '¿Qué haces para recuperar energía después de socializar?',
    'Estar a solas|Dormir|Escuchar música|Caminar|Hacer algo conocido|Reducir estímulos',
    true,
  ),
  poll(
    'social-group-size',
    'Socialización',
    '¿En qué tamaño de grupo te sientes más cómodo/a?',
    'Una persona|Grupo pequeño|Grupo grande|Depende de la actividad',
  ),
  poll(
    'social-invite',
    'Socialización',
    '¿Cómo prefieres recibir una invitación a un plan?',
    'Con anticipación|El mismo día|Con detalles por escrito|Con posibilidad de decidir después',
  ),
  poll(
    'communication-important',
    'Comunicación',
    '¿Cómo prefieres enterarte de algo importante en un grupo?',
    'Mensaje breve|Mensaje fijado|Imagen o resumen|Que me mencionen|Lo reviso cuando pueda',
  ),
  poll(
    'communication-format',
    'Comunicación',
    '¿Qué formatos te resultan cómodos para conversar?',
    'Texto|Audio|Videollamada|Llamada|Cara a cara|Emoji o reacción',
    true,
  ),
  poll(
    'communication-delay',
    'Comunicación',
    '¿Qué te ayuda cuando necesitas responder más tarde?',
    'Marcar como pendiente|Anotar un recordatorio|Dejar el chat abierto|Pedir que me recuerden',
    true,
  ),
  poll(
    'communication-context',
    'Comunicación',
    '¿Qué hace más claro un mensaje grupal?',
    'Asunto al inicio|Resumen breve|Fecha y hora|Enlace relevante|Pregunta concreta',
    true,
  ),
  poll(
    'routine-anchor',
    'Rutinas',
    '¿Qué te ayuda a comenzar una rutina nueva?',
    'Horario fijo|Recordatorio|Preparar materiales|Hacerlo con alguien|Empezar pequeño',
    true,
  ),
  poll(
    'routine-change',
    'Rutinas',
    '¿Cómo prefieres enterarte de un cambio de planes?',
    'Con tiempo|Con un mensaje breve|Con todos los detalles|Por una llamada',
  ),
  poll(
    'routine-morning',
    'Rutinas',
    '¿Qué sueles hacer primero al comenzar el día?',
    'Revisar mensajes|Desayunar|Moverme|Ducharme|Organizar pendientes|Necesito un rato',
  ),
  poll(
    'routine-evening',
    'Rutinas',
    '¿Qué te ayuda a cerrar el día?',
    'Preparar mañana|Bajar pantallas|Música|Ordenar un poco|Conversar',
    true,
  ),
  poll(
    'organize-tools',
    'Organización',
    '¿Qué cosas usas para organizarte?',
    'Calendario|Lista de tareas|Alarmas|Notas en papel|Recordatorios|Temporizador|Ayuda de otra persona|Memoria',
    true,
  ),
  poll(
    'organize-priority',
    'Organización',
    '¿Cómo decides qué tarea hacer primero?',
    'La más urgente|La más corta|La más importante|La que tengo ganas de hacer|Depende del día',
  ),
  poll(
    'organize-reminders',
    'Organización',
    '¿Dónde te resultan más útiles los recordatorios?',
    'Teléfono|Calendario|Papel visible|Chat conmigo mismo/a|Otra persona',
  ),
  poll(
    'organize-plan',
    'Organización',
    '¿Con cuánta anticipación prefieres planear una semana?',
    'El domingo|Uno o dos días antes|Cada mañana|Prefiero improvisar',
  ),
  poll(
    'tech-ai-use',
    'Tecnología',
    '¿En qué tareas te resulta útil la IA cotidiana?',
    'Resumir|Buscar ideas|Organizar|Aprender|Escribir|Programar|Traducir',
    true,
  ),
  poll('tech-headphones', 'Tecnología', '¿Usas auriculares para concentrarte?', 'Sí|No'),
  poll(
    'tech-customization',
    'Tecnología',
    '¿Qué ajustes personalizas en tus dispositivos?',
    'Tema oscuro|Tamaño de letra|Notificaciones|Accesos directos|Brillo|Volumen',
    true,
  ),
  poll(
    'tech-backup',
    'Tecnología',
    '¿Dónde guardas lo que no quieres perder?',
    'Nube|Disco externo|En varios lugares|Solo en el dispositivo|Todavía no hago respaldo',
  ),
  poll(
    'community-content',
    'Comunidad',
    '¿Qué contenido te gustaría ver más en la comunidad?',
    'Consejos cotidianos|Actividades|Recomendaciones|Preguntas|Historias personales|Recursos útiles',
    true,
  ),
  poll(
    'community-participation',
    'Comunidad',
    '¿Cómo te gusta participar en una comunidad online?',
    'Escribiendo|Leyendo|Respondiendo encuestas|Compartiendo recursos|En actividades',
    true,
  ),
  poll(
    'community-comfort',
    'Comunidad',
    '¿Qué hace cómodo un espacio comunitario?',
    'Reglas claras|Respeto|Avisos breves|Ritmo tranquilo|Temas variados|Moderación presente',
    true,
  ),
  poll(
    'community-activity',
    'Comunidad',
    '¿Qué actividad grupal te gustaría probar?',
    'Club de lectura|Partida casual|Ver una película|Intercambio de playlists|Charla temática|Reto creativo',
  ),
  poll(
    'humor-format',
    'Humor',
    '¿Qué tipo de humor compartes más con amistades?',
    'Memes|Videos cortos|Anécdotas|Juegos de palabras|Imágenes|Chistes internos',
  ),
  poll(
    'humor-chat',
    'Humor',
    '¿Qué te hace sonreír en un chat grupal?',
    'Un meme oportuno|Una historia inesperada|Una respuesta ingeniosa|Una foto simpática|Un logro compartido',
    true,
  ),
  poll(
    'humor-response',
    'Humor',
    '¿Cómo reaccionas cuando algo te da mucha risa en un chat?',
    'Emoji|Sticker|Mensaje|Audio|Se lo cuento a alguien',
  ),
  poll('humor-meme', 'Humor', '¿Guardas memes para compartirlos después?', 'Sí|No'),
  poll(
    'study-format',
    'Estudio',
    '¿Qué formato te ayuda a aprender algo nuevo?',
    'Video|Texto|Audio|Ejercicios|Explicación de otra persona|Probar por mi cuenta',
    true,
  ),
  poll(
    'study-desk',
    'Estudio',
    '¿Qué tienes cerca cuando estudias?',
    'Agua|Café o té|Auriculares|Teléfono|Lista de tareas|Temporizador|Snack|Algo para manipular|Cuaderno|Bolígrafo|Lámpara|Calendario',
    true,
  ),
  poll(
    'study-time',
    'Estudio',
    '¿Cuándo prefieres estudiar?',
    'Mañana|Tarde|Noche|Madrugada|Depende del día',
  ),
  poll(
    'study-online',
    'Estudio',
    '¿Qué te gusta de estudiar online?',
    'Pausar contenido|Elegir horario|Volver a ver clases|Evitar traslados|Compartir enlaces',
    true,
  ),
  poll(
    'work-place',
    'Trabajo',
    '¿Dónde trabajas más cómodo/a?',
    'En casa|Oficina|Espacio compartido|Cafetería|Depende de la tarea',
  ),
  poll(
    'work-hybrid',
    'Trabajo',
    '¿Qué te ayuda cuando alternas trabajo presencial y remoto?',
    'Calendario compartido|Rutina de inicio|Lista de pendientes|Pausas|Lugar preparado|Mensajes claros',
    true,
  ),
  poll(
    'work-meeting',
    'Trabajo',
    '¿Qué hace útil una reunión?',
    'Objetivo claro|Agenda|Duración breve|Turnos para hablar|Resumen final|Tareas asignadas',
    true,
  ),
  poll(
    'work-task',
    'Trabajo',
    '¿Qué tipo de tarea prefieres hacer primero?',
    'Concentración profunda|Mensajes rápidos|Planificación|Algo creativo|Lo urgente',
  ),
  poll(
    'sensory-space',
    'Regulación sensorial',
    '¿Qué hace más cómodo un espacio para ti?',
    'Luz ajustable|Poco ruido|Temperatura agradable|Asiento cómodo|Espacio propio|Poder salir un rato|Texturas agradables|Ventilación',
    true,
  ),
  poll(
    'sensory-sound',
    'Regulación sensorial',
    '¿Qué sonido de fondo te resulta más agradable?',
    'Silencio|Lluvia|Música suave|Ruido blanco|Sonidos de naturaleza|Varía según el día',
  ),
  poll(
    'sensory-reset',
    'Regulación sensorial',
    '¿Qué te ayuda cuando un lugar se siente demasiado intenso?',
    'Salir un momento|Auriculares|Bajar la luz|Respirar con calma|Tomar agua|Buscar un lugar tranquilo',
    true,
  ),
  poll(
    'sensory-light',
    'Regulación sensorial',
    '¿Qué iluminación prefieres para una tarde en casa?',
    'Luz natural|Luz cálida|Luz tenue|Luz brillante|Depende de la actividad',
  ),
  poll(
    'energy-recharge',
    'Energía',
    '¿Qué cosas te ayudan a recargar energía?',
    'Dormir|Estar a solas|Moverme|Hablar con alguien|Escuchar música|Jugar|Salir al aire libre|Hacer algo creativo',
    true,
  ),
  poll(
    'energy-peak',
    'Energía',
    '¿Cuándo sueles tener más energía?',
    'Mañana|Mediodía|Tarde|Noche|Cambia mucho',
  ),
  poll(
    'energy-pacing',
    'Energía',
    '¿Qué te ayuda a dosificar energía durante el día?',
    'Pausas|Priorizar tareas|Comer a tiempo|Menos notificaciones|Cambiar de ambiente|Pedir ayuda',
    true,
  ),
  poll(
    'energy-plan',
    'Energía',
    '¿Cómo ajustas tus planes cuando necesitas descansar?',
    'Los pospongo|Los acorto|Pido compañía|Elijo algo tranquilo|Depende del plan',
  ),
  poll(
    'daily-bag',
    'Preferencias cotidianas',
    '¿Qué llevas habitualmente cuando sales?',
    'Agua|Auriculares|Cargador|Algo para leer|Snack|Gafas de sol|Libreta',
    true,
  ),
  poll(
    'daily-drink',
    'Preferencias cotidianas',
    '¿Qué bebida eliges más durante una pausa?',
    'Agua|Café|Té|Jugo|Otra bebida',
  ),
  poll(
    'daily-route',
    'Preferencias cotidianas',
    '¿Cómo prefieres recorrer un lugar nuevo?',
    'Con mapa|Explorando|Con alguien que lo conozca|Planificando antes',
  ),
  poll(
    'daily-weather',
    'Preferencias cotidianas',
    '¿Qué haces para sentirte cómodo/a en un día de mucho calor?',
    'Buscar sombra|Beber agua|Ventilador|Ropa ligera|Quedarme dentro|Salir más tarde',
    true,
  ),
  poll(
    'interest-rabbit-hole',
    'Intereses',
    '¿Qué te hace profundizar en un tema nuevo?',
    'Un video|Una conversación|Un libro|Una pregunta propia|Un juego|Una noticia',
    true,
  ),
  poll(
    'interest-keeping',
    'Intereses',
    '¿Cómo guardas información sobre tus intereses?',
    'Notas|Marcadores|Capturas|Colecciones|Se la envío a alguien|No la guardo',
    true,
  ),
  poll(
    'interest-sharing',
    'Intereses',
    '¿Con quién te gusta compartir un descubrimiento interesante?',
    'Amistades|Familia|Comunidad online|Una persona concreta|Prefiero guardarlo',
  ),
  poll(
    'interest-return',
    'Intereses',
    '¿Vuelves a un tema que te gustaba después de meses?',
    'Sí|No|Depende del tema',
  ),
  poll(
    'plans-notice',
    'Planes',
    '¿Cuánto aviso prefieres antes de una actividad?',
    'Varios días|Un día|Unas horas|Me gustan los planes espontáneos',
  ),
  poll(
    'plans-detail',
    'Planes',
    '¿Qué detalles te sirven antes de aceptar un plan?',
    'Lugar|Duración|Cantidad de personas|Costo|Transporte|Actividad|Posibilidad de salir antes',
    true,
  ),
  poll(
    'plans-indoor',
    'Planes',
    '¿Qué plan bajo techo te apetece más?',
    'Película|Juego de mesa|Cocinar|Conversar|Proyecto creativo|Leer juntos',
  ),
  poll(
    'plans-change',
    'Planes',
    '¿Qué te ayuda si un plan cambia a último momento?',
    'Mensaje claro|Nueva hora|Nueva dirección|Tiempo para decidir|Una alternativa',
    true,
  ),
  poll(
    'online-community',
    'Comunidades online',
    '¿Qué buscas en una comunidad online?',
    'Intereses compartidos|Ayuda práctica|Conversación|Recomendaciones|Eventos|Un ambiente respetuoso',
    true,
  ),
  poll(
    'online-post',
    'Comunidades online',
    '¿Qué te anima a escribir en un grupo online?',
    'Una pregunta clara|Tema conocido|Buen ambiente|Pocas respuestas pendientes|Tiempo para pensar',
    true,
  ),
  poll(
    'online-read',
    'Comunidades online',
    '¿Cómo prefieres seguir una conversación larga?',
    'Resumen fijado|Hilo|Leer desde el inicio|Buscar palabras clave|Pedir contexto',
  ),
  poll(
    'online-boundary',
    'Comunidades online',
    '¿Qué límites te ayudan con los grupos online?',
    'Silenciar|Revisar a ciertas horas|Salir cuando quiera|Pausar notificaciones|Elegir pocos grupos',
    true,
  ),
] as const;

function poll(
  key: string,
  category: string,
  question: string,
  optionList: string,
  allowMultipleAnswers = false,
): DefaultPollTemplate {
  return { key, category, question, options: optionList.split('|'), allowMultipleAnswers };
}

export const POLL_CATEGORIES = [...new Set(DEFAULT_POLL_TEMPLATES.map((item) => item.category))];
