import type { NativePoll } from '../domain/types.js';

export type DefaultPollTemplate = NativePoll & {
  key: string;
  category: string;
};

const optOut = 'Prefiero no responder.';

export const DEFAULT_POLL_TEMPLATES: readonly DefaultPollTemplate[] = [
  poll('mood-today', 'Estado de ánimo general', '¿Cómo te sientes hoy?', [
    'Feliz.',
    'Tranquilo/a.',
    'Cansado/a.',
    'Frustrado/a.',
    optOut,
  ]),
  poll('mood-scale', 'Estado de ánimo general', 'Del 1 al 10, ¿cómo ha estado tu día?', [
    '1.',
    '2.',
    '3.',
    '4.',
    '5.',
    '6.',
    '7.',
    '8.',
    '9.',
    '10.',
    optOut,
  ]),
  poll('energy-today', 'Energía', '¿Cómo está tu energía hoy?', [
    'Muy alta.',
    'Bien.',
    'Regular.',
    'Baja.',
    'Necesito descansar.',
    optOut,
  ]),
  poll('need-today', 'Energía', '¿Qué necesitas más hoy?', [
    'Descansar.',
    'Conversar.',
    'Tener tranquilidad.',
    'Hacer algo entretenido.',
    'Organizarme.',
    optOut,
  ]),
  poll('quiet-afternoon', 'Descanso', '¿Cómo prefieres pasar una tarde tranquila?', [
    'Escuchando música.',
    'Viendo una serie.',
    'Jugando.',
    'Caminando.',
    'Descansando.',
  ]),
  poll('weekly-topic', 'Vida comunitaria', '¿Qué tema te gustaría conversar esta semana?', [
    'Autismo y TDAH.',
    'Experiencias personales.',
    'Hobbies.',
    'Tecnología.',
    'Actividades comunitarias.',
  ]),
  poll('group-activity', 'Actividades', '¿Qué actividad grupal te gustaría?', [
    'Conversación.',
    'Videojuegos.',
    'Películas o series.',
    'Música.',
    'Taller informativo.',
  ]),
  poll('participation-style', 'Comunicación', '¿Cuál es tu forma favorita de participar?', [
    'Escribir mensajes.',
    'Leer solamente.',
    'Responder encuestas.',
    'Compartir información.',
    'Conversar en actividades.',
  ]),
  poll('group-content', 'Vida comunitaria', '¿Qué contenido te gustaría ver más en el grupo?', [
    'Información útil.',
    'Actividades.',
    'Encuestas.',
    'Experiencias.',
    'Recomendaciones.',
  ]),
  poll('hobby-type', 'Intereses y pasatiempos', '¿Qué tipo de hobby disfrutas más?', [
    'Videojuegos.',
    'Música.',
    'Arte.',
    'Lectura.',
    'Actividades al aire libre.',
  ]),
  poll('rest-choice', 'Descanso', '¿Qué prefieres para descansar?', [
    'Música.',
    'Silencio.',
    'Una película.',
    'Un juego.',
    'Dormir.',
  ]),
  poll('weather', 'Preferencias simples', '¿Qué clima prefieres?', [
    'Sol.',
    'Lluvia.',
    'Frío.',
    'Calor.',
    'Nublado.',
  ]),
  poll('day-moment', 'Preferencias simples', '¿Qué momento del día prefieres?', [
    'Mañana.',
    'Mediodía.',
    'Tarde.',
    'Noche.',
    'Madrugada.',
  ]),
  poll('share-choice', 'Preferencias simples', '¿Qué prefieres para compartir?', [
    'Café o té.',
    'Algo dulce.',
    'Algo salado.',
    'Fruta.',
    'Solo conversar.',
  ]),
  poll('content-kind', 'Intereses y pasatiempos', '¿Qué tipo de contenido disfrutas más?', [
    'Comedia.',
    'Acción.',
    'Documentales.',
    'Animación.',
    'Ciencia ficción.',
  ]),
  poll('daily-organization', 'Motivación', '¿Qué te ayuda a organizar mejor el día?', [
    'Una lista.',
    'Una alarma.',
    'Una rutina.',
    'Recordatorios.',
    'Improvisar.',
  ]),
  poll('information-format', 'Comunicación', '¿Cómo prefieres recibir información?', [
    'Texto breve.',
    'Imagen.',
    'Audio.',
    'Video.',
    'Enlaces.',
  ]),
  poll('focus-environment', 'Actividades', '¿Qué ambiente te ayuda a concentrarte?', [
    'Silencio.',
    'Música.',
    'Sonidos ambientales.',
    'Estar acompañado/a.',
    'Depende del día.',
  ]),
  poll('task-order', 'Motivación', '¿Qué prefieres hacer primero?', [
    'Lo más difícil.',
    'Lo más fácil.',
    'Lo más urgente.',
    'Algo entretenido.',
    'Depende del día.',
  ]),
  poll('rest-quality', 'Descanso', '¿Cómo fue tu descanso?', [
    'Muy bueno.',
    'Bueno.',
    'Regular.',
    'Poco.',
    optOut,
  ]),
  poll('community-value', 'Vida comunitaria', '¿Qué valoras más en una comunidad?', [
    'Respeto.',
    'Apoyo.',
    'Información.',
    'Amistad.',
    'Actividades.',
  ]),
  poll('good-coexistence', 'Vida comunitaria', '¿Qué ayuda a mantener una buena convivencia?', [
    'Escuchar.',
    'Respetar.',
    'Ser amable.',
    'Evitar discusiones.',
    'Todas las anteriores.',
  ]),
  poll('most-used-group', 'Vida comunitaria', '¿En qué espacio participas más?', [
    'Conversación General.',
    'Gamer y hobbies.',
    'Sin filtro.',
    'Emergencias y Crisis.',
    'Solo leo los avisos.',
  ]),
  poll('group-events', 'Actividades', '¿Te gustaría participar en actividades grupales?', [
    'Sí.',
    'Tal vez.',
    'Depende de la actividad.',
    'Prefiero actividades escritas.',
    'Por ahora no.',
  ]),
  poll('community-frequency', 'Vida comunitaria', '¿Con qué frecuencia revisas la comunidad?', [
    'Varias veces al día.',
    'Una vez al día.',
    'Algunas veces por semana.',
    'Solo cuando hay avisos.',
    'De vez en cuando.',
  ]),
  poll('week-start', 'Reflexión semanal', '¿Cómo comenzó tu semana?', [
    'Muy bien.',
    'Tranquila.',
    'Ocupada.',
    'Cansadora.',
    'Todavía adaptándome.',
    optOut,
  ]),
  poll('weekly-goal', 'Reflexión semanal', '¿Qué esperas lograr esta semana?', [
    'Descansar mejor.',
    'Organizarme.',
    'Terminar una tarea.',
    'Compartir con alguien.',
    'Avanzar a mi ritmo.',
  ]),
  poll('week-end', 'Reflexión semanal', '¿Cómo terminó tu semana?', [
    'Muy bien.',
    'Bien.',
    'Regular.',
    'Cansadora.',
    optOut,
  ]),
  poll('weekend-plan', 'Fin de semana', '¿Qué prefieres hacer el fin de semana?', [
    'Descansar.',
    'Salir.',
    'Ver series.',
    'Jugar.',
    'Compartir con otras personas.',
  ]),
  poll('close-week', 'Fin de semana', '¿Qué necesitas para cerrar bien la semana?', [
    'Descanso.',
    'Tiempo personal.',
    'Terminar algo pendiente.',
    'Conversar.',
    'Desconectarme un rato.',
  ]),
  poll('lunch-choice', 'Preferencias simples', '¿Qué acompañamiento prefieres al almuerzo?', [
    'Agua.',
    'Jugo.',
    'Té.',
    'Café.',
    'Depende del día.',
  ]),
  poll('small-break', 'Descanso', '¿Qué pausa breve disfrutas más?', [
    'Estirarme.',
    'Escuchar una canción.',
    'Tomar aire.',
    'Mirar por la ventana.',
    'No hacer nada.',
  ]),
  poll('learn-something', 'Motivación', '¿Qué te gustaría aprender por diversión?', [
    'Algo artístico.',
    'Tecnología.',
    'Cocina.',
    'Un idioma.',
    'Un juego nuevo.',
  ]),
  poll('conversation-pace', 'Comunicación', '¿Qué ritmo de conversación prefieres?', [
    'Mensajes breves.',
    'Conversaciones largas.',
    'Responder cuando pueda.',
    'Solo leer.',
    'Depende del tema.',
  ]),
  poll('fiction-place', 'Preguntas ligeras y entretenidas', '¿Qué lugar ficticio visitarías?', [
    'Una nave espacial.',
    'Un mundo de fantasía.',
    'Una ciudad futurista.',
    'Una isla tranquila.',
    'Una escuela de magia.',
  ]),
  poll(
    'free-hour',
    'Preguntas ligeras y entretenidas',
    'Si tuvieras una hora libre, ¿qué elegirías?',
    ['Dormir una siesta.', 'Jugar.', 'Ver algo.', 'Salir a caminar.', 'Escuchar música.'],
  ),
] as const;

function poll(
  key: string,
  category: string,
  question: string,
  options: string[],
  allowMultipleAnswers = false,
): DefaultPollTemplate {
  return { key, category, question, options, allowMultipleAnswers };
}

export const POLL_CATEGORIES = [...new Set(DEFAULT_POLL_TEMPLATES.map((item) => item.category))];
